=== andreferreiracits/educacional_atual/ava/LegacyCompatible/Common/Config/IncDominio.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="incDominio"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="incDominio">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="ie">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="regex"/>
              <xs:element name="sigla">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:length value="3"></xs:length>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="nome" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== andreferreiracits/educacional_atual/ava/LegacyCompatible/Common/Config/IncDominio.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  Arquivo de configuração do Academico_Dominio
  ============================================
  Tag <ie>
    Possui informações para certa escola
    Deve contar as tags <regex>, <sigla> e <nome>
  
  Tag <regex>
    Expressão regular a qual o último site navegado pelo usuário deve
    coincidir
  
  Tag <sigla>
    Academico_Dominio em si
  
  Tag <nome>
    Nome da escola, para fins de conferência
-->
<incDominio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="IncDominio.xsd">
  
  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/fig</regex>
    <sigla>fig</sigla>
    <nome>Faculdades Integradas de Guarulhos</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/unimonte</regex>
    <sigla>ums</sigla>
    <nome>Centro Universitário Monte Serrat</nome>
  </ie>

  <ie>
    <regex>www.faculdadesintegrado.edu.br</regex>
    <sigla>cie</sigla>
    <nome>Faculdade Integrado de Campo Mourão</nome>
  </ie>

  <ie>
    <regex>www.cies.edu.br</regex>
    <sigla>cie</sigla>
    <nome>Faculdade Integrado de Campo Mourão</nome>
  </ie>

  <ie>
    <regex>www.anhanguera.edu.br</regex>
    <sigla>anh</sigla>
    <nome>Centro Universitário de Goiás</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/anhanguera</regex>
    <sigla>anh</sigla>
    <nome>Centro Universitário de Goiás</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/unit</regex>
    <sigla>unt</sigla>
    <nome>Centro Universitário do Triângulo</nome>
  </ie>

  <ie>
    <regex>www.faculdademetodista.edu.br</regex>
    <sigla>fbi</sigla>
    <nome>Faculdade Metodista</nome>
  </ie>

  <ie>
    <regex>local.universitario</regex>
    <sigla>cie</sigla>
    <nome>Faculdade de Testes no Local</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/faculdademetodista</regex>
    <sigla>fbi</sigla>
    <nome>Faculdade Metodista</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/unicenp</regex>
    <sigla>uni</sigla>
    <nome>Universidade Positivo</nome>
  </ie>

  <ie>
    <regex>www.fja.edu.br</regex>
    <sigla>fja</sigla>
    <nome>Faculdades Jorge Amado</nome>
  </ie>

  <ie>
    <regex>www.unicenp.edu.br</regex>
    <sigla>uni</sigla>
    <nome>Universidade Positivo</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/dem</regex>
    <sigla>dem</sigla>
    <nome>Portal Universitário - Demonstração</nome>
  </ie>

  <ie>
    <regex>www.direitorio.fgv.br</regex>
    <sigla>nit</sigla>
    <nome>FGV Niterói</nome>
  </ie>

  <ie>
    <regex>www.metropolitanabh.com.br</regex>
    <sigla>fms</sigla>
    <nome>Faculdade Metropolitana de Belo Horizonte</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d01</regex>
    <sigla>d01</sigla>
    <nome>Portal Universitário - Demonstração - 01</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d02</regex>
    <sigla>d02</sigla>
    <nome>Portal Universitário - Demonstração - 02</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d03</regex>
    <sigla>d03</sigla>
    <nome>Portal Universitário - Demonstração - 03</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d04</regex>
    <sigla>d04</sigla>
    <nome>Portal Universitário - Demonstração - 04</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d05</regex>
    <sigla>d05</sigla>
    <nome>Portal Universitário - Demonstração - 05</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d06</regex>
    <sigla>d06</sigla>
    <nome>Portal Universitário - Demonstração - 06</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d07</regex>
    <sigla>d07</sigla>
    <nome>Portal Universitário - Demonstração - 07</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d08</regex>
    <sigla>d08</sigla>
    <nome>Portal Universitário - Demonstração - 08</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d09</regex>
    <sigla>d09</sigla>
    <nome>Portal Universitário - Demonstração - 09</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d10</regex>
    <sigla>d10</sigla>
    <nome>Portal Universitário - Demonstração - 10</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d11</regex>
    <sigla>d11</sigla>
    <nome>Portal Universitário - Demonstração - 11</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d12</regex>
    <sigla>d12</sigla>
    <nome>Portal Universitário - Demonstração - 12</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d13</regex>
    <sigla>d13</sigla>
    <nome>Portal Universitário - Demonstração - 13</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d14</regex>
    <sigla>d14</sigla>
    <nome>Portal Universitário - Demonstração - 14</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d15</regex>
    <sigla>d15</sigla>
    <nome>Portal Universitário - Demonstração - 15</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d16</regex>
    <sigla>d16</sigla>
    <nome>Portal Universitário - Demonstração - 16</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d17</regex>
    <sigla>d17</sigla>
    <nome>Portal Universitário - Demonstração - 17</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d18</regex>
    <sigla>d18</sigla>
    <nome>Portal Universitário - Demonstração - 18</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d19</regex>
    <sigla>d19</sigla>
    <nome>Portal Universitário - Demonstração - 19</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d20</regex>
    <sigla>d20</sigla>
    <nome>Portal Universitário - Demonstração - 20</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d21</regex>
    <sigla>d21</sigla>
    <nome>Portal Universitário - Demonstração - 21</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d22</regex>
    <sigla>d22</sigla>
    <nome>Portal Universitário - Demonstração - 22</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d23</regex>
    <sigla>d23</sigla>
    <nome>Portal Universitário - Demonstração - 23</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d24</regex>
    <sigla>d24</sigla>
    <nome>Portal Universitário - Demonstração - 24</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d25</regex>
    <sigla>d25</sigla>
    <nome>Portal Universitário - Demonstração - 25</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d26</regex>
    <sigla>d26</sigla>
    <nome>Portal Universitário - Demonstração - 26</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d27</regex>
    <sigla>d27</sigla>
    <nome>Portal Universitário - Demonstração - 27</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d28</regex>
    <sigla>d28</sigla>
    <nome>Portal Universitário - Demonstração - 28</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d29</regex>
    <sigla>d29</sigla>
    <nome>Portal Universitário - Demonstração - 29</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d30</regex>
    <sigla>d30</sigla>
    <nome>Portal Universitário - Demonstração - 30</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d31</regex>
    <sigla>d31</sigla>
    <nome>Portal Universitário - Demonstração - 31</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d32</regex>
    <sigla>d32</sigla>
    <nome>Portal Universitário - Demonstração - 32</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d33</regex>
    <sigla>d33</sigla>
    <nome>Portal Universitário - Demonstração - 33</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d34</regex>
    <sigla>d34</sigla>
    <nome>Portal Universitário - Demonstração - 34</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d35</regex>
    <sigla>d35</sigla>
    <nome>Portal Universitário - Demonstração - 35</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d36</regex>
    <sigla>d36</sigla>
    <nome>Portal Universitário - Demonstração - 36</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d37</regex>
    <sigla>d37</sigla>
    <nome>Portal Universitário - Demonstração - 37</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d38</regex>
    <sigla>d38</sigla>
    <nome>Portal Universitário - Demonstração - 38</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d39</regex>
    <sigla>d39</sigla>
    <nome>Portal Universitário - Demonstração - 39</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d40</regex>
    <sigla>d40</sigla>
    <nome>Portal Universitário - Demonstração - 40</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d41</regex>
    <sigla>d41</sigla>
    <nome>Portal Universitário - Demonstração - 41</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d42</regex>
    <sigla>d42</sigla>
    <nome>Portal Universitário - Demonstração - 42</nome>
  </ie>

  <ie>
    <regex>universitario.educacional.com.br/ensinosuperior/d43</regex>
    <sigla>d43</sigla>
